app:
  name: "Juan Antonio Arroyes"
  email: "arroyes89@gmail.com"

spring:
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS DB
      username: sa
      password: sa
  h2:
    console:
      enabled: true
  application:
    name: apispaceinvaders

---
spring.profiles: dev
