app:
  name: "Juan Antonio Arroyes"
  email: "arroyes89@gmail.com"
  logpath: ./data
  savegamepath: ./data/savegames

spring:
  datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS DB
      username: sa
      password: sa
  h2:
    console:
      enabled: true
  application:
    name: apispaceinvaders

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    defaults:
      enabled: false
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always

---
spring.profiles: dev




