app:
  name: "Juan Antonio Arroyes"
  email: "arroyes89@gmail.com"
  logpath: ./data

spring:
  application:
    name: apispaceinvaders

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    db:
      enabled: true
    defaults:
      enabled: false
    diskspace:
      enabled: true
  endpoint:
    health:
      show-details: always

---
spring.profiles: dev
